# Generated by Django 4.1.1 on 2023-05-11 10:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_healthy_tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.CharField(max_length=30, null=True)),
                ('tip', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='admin_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dietition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_Username', models.CharField(max_length=30, null=True)),
                ('diet_Name', models.CharField(max_length=30, null=True)),
                ('diet_Date_of_Birth', models.DateField(null=True)),
                ('diet_Qualifications', models.CharField(max_length=30, null=True)),
                ('diet_Experience', models.CharField(max_length=30, null=True)),
                ('diet_Mobile_no', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('diet_password', models.IntegerField(null=True)),
                ('diet_Image', models.ImageField(null=True, upload_to='uploadedimages')),
                ('diet_approvement', models.CharField(max_length=30, null=True)),
                ('rating', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('images', models.ImageField(null=True, upload_to='videos')),
                ('image_name', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lullaby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('lullaby', models.FileField(null=True, upload_to='videos')),
                ('lullaby_name', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.CharField(max_length=1000000)),
                ('room', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='paid_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=30, null=True)),
                ('card_number', models.IntegerField(null=True)),
                ('expiry_date', models.CharField(max_length=30, null=True)),
                ('security_code', models.IntegerField(null=True)),
                ('postal_code', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('story', models.FileField(null=True, upload_to='videos')),
                ('story_name', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vaccine_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_age', models.CharField(max_length=50, null=True)),
                ('vaccine_name', models.CharField(max_length=50, null=True)),
                ('v_dose', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('videos', models.FileField(null=True, upload_to='videos')),
                ('video_name', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='users_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, null=True)),
                ('child_name', models.CharField(max_length=30, null=True)),
                ('parent_name', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('birth_date', models.DateField(max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='uploadedimages')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('users_approve', models.CharField(max_length=30, null=True)),
                ('contact_number', models.IntegerField(null=True)),
                ('password', models.IntegerField(null=True)),
                ('userr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=30, null=True)),
                ('Name_of_dietition', models.CharField(max_length=30, null=True)),
                ('feedback', models.CharField(max_length=30, null=True)),
                ('rating', models.CharField(max_length=30, null=True)),
                ('userr_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users_reg')),
            ],
        ),
        migrations.CreateModel(
            name='user_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('diet_name', models.CharField(max_length=30, null=True)),
                ('admin_reply', models.CharField(default='waiting for admin reply', max_length=500)),
                ('issues', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users_reg')),
            ],
        ),
        migrations.CreateModel(
            name='user_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('name_of_dietition', models.CharField(max_length=30, null=True)),
                ('choose_a_plan', models.CharField(max_length=30, null=True)),
                ('duration_of_plan', models.CharField(max_length=30, null=True)),
                ('payment_amount', models.IntegerField(null=True)),
                ('chat_code', models.CharField(max_length=30, null=True)),
                ('userr_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dietition')),
            ],
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_three_month', models.IntegerField(null=True)),
                ('ex_six_month', models.IntegerField(null=True)),
                ('ex_one_yr', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dietition')),
            ],
        ),
        migrations.CreateModel(
            name='diet_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_name', models.CharField(max_length=30, null=True)),
                ('chart_heading', models.CharField(max_length=5000, null=True)),
                ('explanation', models.CharField(max_length=5000, null=True)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dietition')),
            ],
        ),
        migrations.CreateModel(
            name='add_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_three_month', models.IntegerField(null=True)),
                ('std_six_month', models.IntegerField(null=True)),
                ('std_one_yr', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dietition')),
            ],
        ),
    ]
