# Generated by Django 4.1.1 on 2023-05-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet_chart',
            old_name='diet',
            new_name='diets',
        ),
    ]
