# Generated by Django 4.1.7 on 2023-05-12 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_users_reg_payment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet_chart',
            name='charts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.users_reg'),
            preserve_default=False,
        ),
    ]
