# Generated by Django 4.1.7 on 2023-05-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_diet_chart_charts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_reg',
            name='payment_done',
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='payment_done',
            field=models.CharField(default='no', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user_appointment',
            name='userr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.users_reg'),
            preserve_default=False,
        ),
    ]
