# Generated by Django 4.2 on 2023-05-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_users_reg_payment_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietition',
            name='diet_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_reg',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
