# Generated by Django 4.2 on 2023-05-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_dietition_diet_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet_chart',
            name='charts',
        ),
    ]
